name: build

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npx prettier --check '**/*.{md,yml}'
